added AuthenticationFilter, AuthenticationService, JwtUtil;
mykolaskrypka/OnlineBookStore pull request #11
Opened 2023-12-21 13:08 UTC by mykolaskrypka

I do not know why - requestMatchers("/auth/**") do not working

2023-12-21 16:08 UTC, mykolaskrypka commented
Please help, can not find why it still goes through the AuthenticateFilter when i make request to the /api/auth/login endpoint

2023-12-21 19:22 UTC, Sanderfuck requested changes

2023-12-21 19:22 UTC, Sanderfuck commented on src/main/java/mate/academy/security/AuthenticationFilter.java
> +            );
```suggestion
                    userDetails, null, userDetails.getAuthorities());
```

2023-12-21 19:22 UTC, Sanderfuck commented on src/main/java/mate/academy/security/AuthenticationFilter.java
> +
```suggestion
```

2023-12-21 19:22 UTC, Sanderfuck commented on src/main/java/mate/academy/security/AuthenticationService.java
> +        );
Don`t replace ); for new line, it make no sense and looks not good

2023-12-21 19:22 UTC, Sanderfuck commented on src/main/java/mate/academy/security/AuthenticationService.java
> +
```suggestion
```

2023-12-21 19:22 UTC, Sanderfuck commented on src/main/java/mate/academy/security/JwtUtil.java
> +
```suggestion
```

2023-12-21 20:30 UTC, mykolaskrypka commented on src/main/java/mate/academy/security/JwtUtil.java
> +
@Sanderfuck please, read the comment

2023-12-22 09:49 UTC, Rommelua commented on src/main/java/mate/academy/controller/TestController.java
> +public class TestController {
delete it

2023-12-22 09:55 UTC, mykolaskrypka commented on src/main/java/mate/academy/controller/TestController.java
> +public class TestController {
@Rommelua need help, why it still goes through the AuthenticateFilter when i make request to the /api/auth/login endpoint

2024-01-24 10:19 UTC, merged