SpingBootWeb
mykolaskrypka/OnlineBookStore pull request #3
Opened 2023-10-19 13:35 UTC by mykolaskrypka

added dto's and mapper

2023-10-19 18:37 UTC, Sanderfuck requested changes

2023-10-19 18:37 UTC, Sanderfuck commented on src/main/java/mate/academy/repository/BookDaoImpl.java
> +            throw new EntityNotFoundException("Can't get all books from db", e);
Check Exception message

2023-10-19 18:37 UTC, Sanderfuck commented on src/main/java/mate/academy/repository/BookDaoImpl.java
>          Transaction transaction = null;
For what this?

2023-10-19 18:37 UTC, Sanderfuck commented on src/main/java/mate/academy/dto/CreateBookRequestDto.java
> +public class CreateBookRequestDto {
Why you choose this naming of entity?

2023-10-19 19:33 UTC, mykolaskrypka commented on src/main/java/mate/academy/dto/CreateBookRequestDto.java
> +public class CreateBookRequestDto {
![spWeb](https://github.com/mykolaskrypka/OnlineBookStore/assets/90352164/9e18010e-25a7-47bd-a81f-750a619b85a3)

2023-10-19 19:40 UTC, mykolaskrypka commented on src/main/java/mate/academy/repository/BookDaoImpl.java
>          Transaction transaction = null;
this part is missing in the current version
![spWeb2](https://github.com/mykolaskrypka/OnlineBookStore/assets/90352164/65e9cf6c-563b-40d5-93ab-55adf8be7d40)

2023-10-19 19:45 UTC, mykolaskrypka commented on src/main/java/mate/academy/repository/BookDaoImpl.java
> +            throw new EntityNotFoundException("Can't get all books from db", e);
what do you mean?

2023-10-20 11:42 UTC, kerrrusha approved these changes

2023-10-20 11:42 UTC, kerrrusha commented on src/main/java/mate/academy/controller/BookController.java
> +
redundant blank line

2023-10-24 06:04 UTC, merged