Security basics
mykolaskrypka/OnlineBookStore pull request #9
Opened 2023-12-12 07:32 UTC by mykolaskrypka

2023-12-12 12:35 UTC, Sanderfuck requested changes

2023-12-12 12:35 UTC, Sanderfuck commented on src/main/java/mate/academy/dto/UserRegistrationRequestDto.java
> +    private String email;
Is it enough for validate email?

2023-12-13 10:48 UTC, Rommelua commented on src/main/java/mate/academy/dto/UserRegistrationRequestDto.java
> +    @ValidEmail
```suggestion
    @Email
```

2023-12-13 10:48 UTC, Rommelua commented on src/main/java/mate/academy/dto/UserRegistrationRequestDto.java
> +import mate.academy.validation.ValidEmail;
```suggestion
import jakarta.validation.constraints.ValidEmail;
```

2023-12-13 10:48 UTC, Rommelua commented on src/main/java/mate/academy/validation/EmailValidator.java
> +public class EmailValidator implements ConstraintValidator<ValidEmail, String> {
No reason for custom validation

2023-12-13 10:48 UTC, Rommelua commented on src/main/java/mate/academy/validation/FieldMatchValidator.java
> +public class FieldMatchValidator implements ConstraintValidator<FieldMatch, Object> {
```suggestion
public class FieldMatchValidator implements ConstraintValidator<FieldMatch, UserRegistrationRequestDto> {
```

2023-12-14 20:11 UTC, merged